### ISSUE TITLE
Support build on macOS BigSur(11.2.3)

### ISSUE THREAD

**Issue by purelind** [pingcap/tiflash#2267]
### add support for macOS BigSur
* build on mac-mini(intel chip) with macOS BigSur(11.2.3), Compilation errors encountered. 
* current release darwin binary only works on an old mac-mini with macOS Catalina(10.15.6)
