### PR TITLE
fix build fail in mac introduce by https://github.com/pingcap/tiflash/pull/7584

### LINKED ISSUE #7610: build fail in mac introduced by https://github.com/pingcap/tiflash/pull/7584
```
/Users/pingcap/workspace/build-common@2/go/src/[github.com/pingcap/tics/dbms/src/Flash/Pipeline/Schedule/Tasks/TaskProfileInfo.h:124:33](http://github.com/pingcap/tics/dbms/src/Flash/Pipeline/Schedule/Tasks/TaskProfileInfo.h:124:33): error: use of undeclared identifier 'type_cpu_execute'
        REPORT_DURATION_METRICS(type_cpu_execute, cpu_execute_time_ns);
                                ^
/Users/pingcap/workspace/build-common@2/go/src/[github.com/pingcap/tics/dbms/src/Flash/Pipeline/Schedule/Tasks/TaskProfileInfo.h:125:33](http://github.com/pingcap/tics/dbms/src/Flash/Pipeline/Schedule/Tasks/TaskProfileInfo.h:125:33): error: use of undeclared identifier 'type_cpu_queue'
        REPORT_DURATION_METRICS(type_cpu_queue, cpu_pending_time_ns);
                                ^
/Users/pingcap/workspace/build-common@2/go/src/[github.com/pingcap/tics/dbms/src/Flash/Pipeline/Schedule/Tasks/TaskProfileInfo.h:126:33](http://github.com/pingcap/tics/dbms/src/Flash/Pipeline/Schedule/Tasks/TaskProfileInfo.h:126:33): error: use of undeclared identifier 'type_io_execute'
        REPORT_DURATION_METRICS(type_io_execute, io_execute_time_ns);
                                ^
/Users/pingcap/workspace/build-common@2/go/src/[github.com/pingcap/tics/dbms/src/Flash/Pipeline/Schedule/Tasks/TaskProfileInfo.h:127:33](http://github.com/pingcap/tics/dbms/src/Flash/Pipeline/Schedule/Tasks/TaskProfileInfo.h:127:33): error: use of undeclared identifier 'type_io_queue'
        REPORT_DURATION_METRICS(type_io_queue, io_pending_time_ns);
                                ^
/Users/pingcap/workspace/build-common@2/go/src/[github.com/pingcap/tics/dbms/src/Flash/Pipeline/Schedule/Tasks/TaskProfileInfo.h:128:33](http://github.com/pingcap/tics/dbms/src/Flash/Pipeline/Schedule/Tasks/TaskProfileInfo.h:128:33): error: use of undeclared identifier 'type_await'
        REPORT_DURATION_METRICS(type_await, await_time_ns);
                                ^
5 errors generated.
```

### PR DESCRIPTION
**Pull request by SeaRise**
### What problem does this PR solve?

Issue Number: close #7610

Problem Summary:

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

### CODE REVIEW

**Review by yibin87 — APPROVED** [review]
LGTM

**Review by JaySon-Huang — APPROVED** [review]

**Review by Lloyd-Pottiger — APPROVED** [review]
